Get-ReportingApp/config/routes.rb
Rails.application.routes.draw do

  
  resources :connections  
  resources :reports 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Get-ReportingApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Get-ReportingApp/app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :report, inverse_of: :connections
end

Get-ReportingApp/app/models/report.rb
class Report < ApplicationRecord
    has_many :connections, inverse_of: :report
end

Get-ReportingApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Get-ReportingApp/app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def index
    #@connections = Connection.order(:name).limit(100)
    
    @connections = Connection.all
  end

  def show
    
  end

  def new
  end

  def edit
  end
end

Get-ReportingApp/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
    #@connections = Connection.order(:id).limit(10)
  end

  def show
    id = params[:id]
    puts "id is #{id}"
    @connections = Connection.where(:report => id)
    thisconnection = Connection.find(1)
    puts "thisconnection cpm is #{thisconnection.cpm}"
  end

  def new
  end

  def edit
  end
end

Get-ReportingApp/app/helpers/application_helper.rb
module ApplicationHelper
end

Get-ReportingApp/app/helpers/connections_helper.rb
module ConnectionsHelper
end

Get-ReportingApp/app/helpers/reports_helper.rb
module ReportsHelper
end

Get-ReportingApp/app/views/connections/edit.html.erb
<h1>Connections#edit</h1>
<p>Find me in app/views/connections/edit.html.erb</p>

Get-ReportingApp/app/views/connections/index.html.erb
<head>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://editor.datatables.net/extensions/Editor/css/editor.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchbuilder/1.0.0/css/searchBuilder.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowgroup/1.1.2/css/rowGroup.dataTables.min.css">


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
<script src="https://cdn.datatables.net/searchbuilder/1.0.0/js/dataTables.searchBuilder.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/rowgroup/1.1.2/js/dataTables.rowGroup.min.js"></script>


</head>
<h1>Connections</h1>


<script>


$(document).ready( function () {
   var table = $('#table_id').DataTable({
        rowGroup: {
            dataSrc: [],
    },
    buttons:[
        {
            extend: 'searchBuilder',
            config: {
                depthLimit: 4
            }
        }
        ,
        'copy'
    ],
    dom: 'Qlfrtip',
    searchBuilder: {
        preDefined: {
            criteria:[
                {
                    condition: 'between',
                    data: 'date',
                    value: []
                }
            ],
            logic: 'AND',
        }
    },
    dom: 'Bfrtip',
}); //end DataTable();

      $('#checkConnections').click((event) => {
        
            table.rowGroup().dataSrc([1]);
            console.log(1, "In #checkConnections", event)
            table.rowGroup().enable().draw();
        
         
             //table.rowGroup().disable().draw();
         
     })
        $('#checkApp').click((event) => {
         
            table.rowGroup().dataSrc([2,3,4]);
            console.log(2, "In #checkApp")
            table.rowGroup().enable().draw();
       
         
     })
        $('#checkPlatform').click((event) => {
         if(event.target.checked){
            table.rowGroup().dataSrc([]);
            console.log(3, "In #checkPatform")
            table.rowGroup().enable().draw();
         } else {
             //table.rowGroup().disable().draw();
         }
         
     })
        $('#checkCountry').click((event) => {
         if(event.target.checked){
            table.rowGroup().dataSrc([4]);
            console.log(4, "In #checkCountry")
            table.rowGroup().enable().draw();
         } else {
             //table.rowGroup().disable().draw();
         }
         
     })

} );
</script>
<%# <button id="groupByApp" type="checkbox">group by app</button> %>

<script>


</script>


Connections: <input type="checkbox" id="checkConnections">
App: <input type="checkbox" id="checkApp">
Platform: <input type="checkbox" id="checkPlatform">
Country: <input type="checkbox" id="checkCountry">

<table id="table_id" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Connection Type</th>
            <th>App</th>
            <th>Platform</th>
            <th>Country</th>
            <th>Date</th>
            <th>Impressions</th>
            <th>Ad Revenue</th>
            <th>CPM</th>
        </tr>
    </thead>
    <tbody>  
            <% @connections.each do |connection| %>
                <tr>
                    <td><%=connection.name%></td>
                    <td><%=connection.connection%></td>
                    <td><%=connection.app%></td>
                    <td><%=connection.platform%></td>
                    <td><%=connection.country%></td>
                    <td><%=connection.date%></td>
                    <td><%=connection.impressions.to_d%></td>
                    <td><%=connection.ad_revenue.to_d%></td>
                    <td><%=connection.cpm.to_d%></td>
                </tr>
            <% end %>
    </tbody>
</table>

Get-ReportingApp/app/views/connections/new.html.erb
<h1>Connections#new</h1>
<p>Find me in app/views/connections/new.html.erb</p>

Get-ReportingApp/app/views/connections/show.html.erb
<h1>Connections#show</h1>
<p>Find me in app/views/connections/show.html.erb</p>


<%= link_to 'Remove', @connection, method: :delete, data: { confirm: 'Are you sure?' } %>

Get-ReportingApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetReportingapp</title>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://editor.datatables.net/extensions/Editor/css/editor.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchbuilder/1.0.0/css/searchBuilder.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowgroup/1.1.2/css/rowGroup.dataTables.min.css">


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
<script src="https://cdn.datatables.net/searchbuilder/1.0.0/js/dataTables.searchBuilder.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/rowgroup/1.1.2/js/dataTables.rowGroup.min.js"></script>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Get-ReportingApp/app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

Get-ReportingApp/app/views/reports/index.html.erb
<h1>Reports</h1>


<ul>
  <% @reports.each do |report| %>
    <li><%= link_to report.name, report_url(report)  %></li>
  <% end %>
</ul>

Get-ReportingApp/app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

Get-ReportingApp/app/views/reports/show.html.erb
<h1>Connections</h1>

<script>
$(document).ready( function () {
   var table = $('#table_id').DataTable({
        rowGroup: {
            //dataSrc: [],
    },
    buttons:[
        {
            extend: 'searchBuilder',
            config: {
                depthLimit: 4
            }
        }
    ],
    
    "pageLength": 100,

    dom: 'Qlfrtip',
    searchBuilder: {
        preDefined: {
            criteria:[
                {
                    condition: 'between',
                    data: 'Date',
                    value: []
                }
            ],
            logic: 'AND',
        }
    },
    
    // endRender: function ( rows, group ) {
    //     var avg = rows
    //         .data()
    //         .pluck('cpm')
    //         .reduce( function (a, b) {
    //             return a + b.replace(/[^\d]/g, '')*1;
    //         }, 0) / rows.count();

    //     return 'Average CPM in '+group+': '+
    //         $.fn.dataTable.render.number(',', '.', 0, '$').display( avg );
    // }
    
} );
var getChecboxesState = () => {
    var connections = $('#checkConnections').prop('checked')
    var app = $('#checkApp').prop('checked')
    var platform = $('#checkPlatform').prop('checked')
    var country = $('#checkCountry').prop('checked')

    var columnsIndicesToInclude = [
        ...(connections ? [1] : []),
        ...(app ? [2] : []),
        ...(platform ? [3] : []),
        ...(country ? [4] : []),
    ];
    return columnsIndicesToInclude;
}


$('#checkConnections, #checkApp, #checkPlatform, #checkCountry').click(() => {
    var indicesToInclude = getChecboxesState();
    console.log('indicesToInclude', indicesToInclude)
    table.rowGroup().dataSrc(indicesToInclude);
    table.rowGroup().enable().draw();
})

}); //end DataTable();

</script>

<span><b>Group by:</b></span><br>
<label for="checkConnections">Connections</label> <input type="checkbox" id="checkConnections"><br>
App: <input type="checkbox" id="checkApp"><br>
Platform: <input type="checkbox" id="checkPlatform"><br>
Country: <input type="checkbox" id="checkCountry"><br>

<table id="table_id" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Connection Type</th>
            <th>App</th>
            <th>Platform</th>
            <th>Country</th>
            <th>Date</th>
            <th>Impressions</th>
            <th>Ad Revenue</th>
            <th>CPM</th>
        </tr>
    </thead>
    <tbody>  
            <% @connections.each do |connection| %>
                <tr>
                    <td><%=connection.name%></td>
                    <td><%=connection.connection%></td>
                    <td><%=connection.app%></td>
                    <td><%=connection.platform%></td>
                    <td><%=connection.country%></td>
                    <td><%=connection.date%></td>
                    <td><%=connection.impressions%></td>
                    <td><%=connection.ad_revenue%></td>
                    <td><%=connection.cpm%></td>
                </tr>
            <% end %>
    </tbody>
</table>